name: Build docker image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      service:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{inputs.env}}
      
      - name: setup env and args
        run: echo ${{inputs.env}} | base64 --decode > .actions-env
        
      - run: cat .actions-env

      - name: build image
        run: >
         docker build $(awk '{ sub ("\\\\$", " "); printf " --build-arg %s", $0  } END { print ""  }' .actions-env) -t ${{ inputs.service }} .
