name: Build docker image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      iv:
        required: true
      key:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: args-artifact
          path: .
      
      - name: decrypt file
        run: openssl enc -aes-256-cbc -nosalt -d -in args.enc -out .actions-env -K '${{secrets.key}}' -iv '${{secrets.iv}}'
        
      - name: build image
        run: >
         docker build $(awk '{ sub ("\\\\$", " "); printf " --build-arg %s", $0  } END { print ""  }' .actions-env) -t ${{ inputs.service }} .
