name: Build docker image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: args-artifact
          path: .
      
      - name: decrypt file
        run: openssl enc -aes-256-cbc -nosalt -d -in file.enc -out .actions-env -K '${{secrets.ENCRYPT_FILE_KEY}}' -iv '${{secrets.ENCRYPT_FILE_IV}}'
        
      - run: cat .actions-env

      - name: build image
        run: >
         docker build $(awk '{ sub ("\\\\$", " "); printf " --build-arg %s", $0  } END { print ""  }' .actions-env) -t ${{ inputs.service }} .
