name: Format Vault secrets to args and env

on:
  workflow_call:
    inputs:
      vault-path:
        required: true
        type: string
    outputs:
      args:
        value: ${{ jobs.format.outputs.output1 }}
    secrets:
      token:
        required: true 

jobs:
  format:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.return.outputs.args }}
    steps:
      - uses: actions/checkout@v2

      - name: Import Secrets
        uses: matryxxx02/vault-action@v1.0.11
        with:
            url: https://vault.tabuleo.fr
            token: ${{ secrets.token }}
            tlsSkipVerify: true
            secrets: ${{ inputs.vault-path }} *      
      
      - name: Parse JSON secrets to env
        run: echo $JSON | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > .actions-env
        env:
          JSON: ${{ toJSON(env) }}
          
      - run: cat .actions-env
      
      - name: Return env
        run: echo "::set-output name=args::$(base64 .actions-env)"
